#[derive(Debug, Clone, PartialEq)]
#[allow(dead_code)]
pub enum TokenKind {
    // Literals
    IntegerLiteral,
    FloatLiteral,
    StringLiteral,
    CharLiteral,
    HexLiteral,
    Identifier,

    // Keywords
    Program,
    Unit,
    Library,
    Package,
    Interface,
    Implementation,
    Initialization,
    Finalization,
    Uses,
    Type,
    Const,
    Var,
    Begin,
    End,
    If,
    Then,
    Else,
    Case,
    Of,
    For,
    To,
    DownTo,
    Do,
    While,
    Repeat,
    Until,
    With,
    Try,
    Except,
    Finally,
    Raise,
    On,
    As,
    In,
    Is,
    Not,
    And,
    Or,
    Xor,
    Div,
    Mod,
    Shl,
    Shr,
    Procedure,
    Function,
    Constructor,
    Destructor,
    Property,
    Class,
    Record,
    Object,
    DispInterface,
    Array,
    Set,
    File,
    String,
    Packed,
    Goto,
    Label,
    Nil,
    Inherited,
    Abstract,
    Virtual,
    Override,
    Overload,
    Reintroduce,
    Static,
    Default,
    Stored,
    Message,
    Dynamic,
    Inline,
    Asm,
    Out,
    External,
    Forward,
    Public,
    Published,
    Protected,
    Private,
    Strict,
    Read,
    Write,
    Index,
    Nodefault,
    Helper,
    At,
    ThreadVar,
    Cdecl,
    Stdcall,
    Register,
    Pascal,
    Safecall,
    Implements,

    // Symbols
    Plus,
    Minus,
    Star,
    Slash,
    Assign,
    Equal,
    NotEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Comma,
    Semicolon,
    Colon,
    Dot,
    DotDot,
    Caret,
    AtSign,

    // Special
    Eof,
    DirectiveCompiler,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub text: String,
    pub line: usize,
    pub col: usize,
}

impl Token {
    pub fn new(kind: TokenKind, text: String, line: usize, col: usize) -> Self {
        Self {
            kind,
            text,
            line,
            col,
        }
    }
}

#[allow(dead_code)]
pub fn keyword_or_ident(text: &str) -> TokenKind {
    match text.to_uppercase().as_str() {
        "PROGRAM" => TokenKind::Program,
        "UNIT" => TokenKind::Unit,
        "LIBRARY" => TokenKind::Library,
        "PACKAGE" => TokenKind::Package,
        "INTERFACE" => TokenKind::Interface,
        "IMPLEMENTATION" => TokenKind::Implementation,
        "INITIALIZATION" => TokenKind::Initialization,
        "FINALIZATION" => TokenKind::Finalization,
        "USES" => TokenKind::Uses,
        "TYPE" => TokenKind::Type,
        "CONST" => TokenKind::Const,
        "VAR" => TokenKind::Var,
        "BEGIN" => TokenKind::Begin,
        "END" => TokenKind::End,
        "IF" => TokenKind::If,
        "THEN" => TokenKind::Then,
        "ELSE" => TokenKind::Else,
        "CASE" => TokenKind::Case,
        "OF" => TokenKind::Of,
        "FOR" => TokenKind::For,
        "TO" => TokenKind::To,
        "DOWNTO" => TokenKind::DownTo,
        "DO" => TokenKind::Do,
        "WHILE" => TokenKind::While,
        "REPEAT" => TokenKind::Repeat,
        "UNTIL" => TokenKind::Until,
        "WITH" => TokenKind::With,
        "TRY" => TokenKind::Try,
        "EXCEPT" => TokenKind::Except,
        "FINALLY" => TokenKind::Finally,
        "RAISE" => TokenKind::Raise,
        "ON" => TokenKind::On,
        "AS" => TokenKind::As,
        "IN" => TokenKind::In,
        "IS" => TokenKind::Is,
        "NOT" => TokenKind::Not,
        "AND" => TokenKind::And,
        "OR" => TokenKind::Or,
        "XOR" => TokenKind::Xor,
        "DIV" => TokenKind::Div,
        "MOD" => TokenKind::Mod,
        "SHL" => TokenKind::Shl,
        "SHR" => TokenKind::Shr,
        "PROCEDURE" => TokenKind::Procedure,
        "FUNCTION" => TokenKind::Function,
        "CONSTRUCTOR" => TokenKind::Constructor,
        "DESTRUCTOR" => TokenKind::Destructor,
        "PROPERTY" => TokenKind::Property,
        "CLASS" => TokenKind::Class,
        "RECORD" => TokenKind::Record,
        "OBJECT" => TokenKind::Object,
        "DISPINTERFACE" => TokenKind::DispInterface,
        "ARRAY" => TokenKind::Array,
        "SET" => TokenKind::Set,
        "FILE" => TokenKind::File,
        "STRING" => TokenKind::String,
        "PACKED" => TokenKind::Packed,
        "GOTO" => TokenKind::Goto,
        "LABEL" => TokenKind::Label,
        "NIL" => TokenKind::Nil,
        "INHERITED" => TokenKind::Inherited,
        "ABSTRACT" => TokenKind::Abstract,
        "VIRTUAL" => TokenKind::Virtual,
        "OVERRIDE" => TokenKind::Override,
        "OVERLOAD" => TokenKind::Overload,
        "REINTRODUCE" => TokenKind::Reintroduce,
        "STATIC" => TokenKind::Static,
        "MESSAGE" => TokenKind::Message,
        "DYNAMIC" => TokenKind::Dynamic,
        "INLINE" => TokenKind::Inline,
        "ASM" => TokenKind::Asm,
        "OUT" => TokenKind::Out,
        "EXTERNAL" => TokenKind::External,
        "FORWARD" => TokenKind::Forward,
        "PUBLIC" => TokenKind::Public,
        "PUBLISHED" => TokenKind::Published,
        "PROTECTED" => TokenKind::Protected,
        "PRIVATE" => TokenKind::Private,
        "STRICT" => TokenKind::Strict,
        "HELPER" => TokenKind::Helper,
        "AT" => TokenKind::At,
        "THREADVAR" => TokenKind::ThreadVar,
        "CDECL" => TokenKind::Cdecl,
        "STDCALL" => TokenKind::Stdcall,
        "REGISTER" => TokenKind::Register,
        "PASCAL" => TokenKind::Pascal,
        "SAFECALL" => TokenKind::Safecall,
        _ => TokenKind::Identifier,
    }
}
